sudo: required
language: groovy
jdk:
  - openjdk8
  - openjdk11
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
install: "./etc/travis-setup.sh"
script: "./gradlew check -i -x groovydoc"
after_script: heroku keys:remove $USER@`hostname`
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
